export interface EnvVar {
  key: string
  value: string
  comment?: string | undefined
  isCustom?: boolean | undefined
}

export interface EnvFile {
  vars: Map<string, EnvVar>
  order: string[]
  trailingContent: string
  sourceVars?: Record<string, string> | undefined
}

export const VARS_MARKER_PREFIX = '# envi:vars='

const GENERATED_HEADER_TEXT = '🔑 Auto-generated by envi cli'
const LOCAL_ENVS_SEPARATOR_TEXT = '👇 PUT YOUR CUSTOM ENVS BELOW THIS LINE'
const MIN_SIDE_DASHES = 4

function createSectionComment(text: string): string {
  const longestTextLength = Math.max(GENERATED_HEADER_TEXT.length, LOCAL_ENVS_SEPARATOR_TEXT.length)
  const totalDashes = longestTextLength - text.length + MIN_SIDE_DASHES * 2
  const leftDashes = Math.floor(totalDashes / 2)
  const rightDashes = totalDashes - leftDashes
  return `# ${'─'.repeat(leftDashes)} ${text} ${'─'.repeat(rightDashes)}`
}

export const GENERATED_FILE_HEADER = createSectionComment(GENERATED_HEADER_TEXT)

export type ChangeType = 'new' | 'updated' | 'local_modified' | 'custom' | 'unchanged'

export interface Change {
  type: ChangeType
  key: string
  templateValue?: string | undefined
  localValue?: string | undefined
  newValue?: string | undefined
}

export const LOCAL_ENVS_SEPARATOR = createSectionComment(LOCAL_ENVS_SEPARATOR_TEXT)
